### ISSUE TITLE
Production Stable Roadmap

### ISSUE THREAD

**Issue by abhibeckert** [alexandre-daubois/phikl#9]
> This library is still in development and is not yet ready for production use.

Can we please clarify what is left before this product can be used in production? I would like to use it in production and am happy to put in whatever work is necessary to get it there.

**Comment by alexandre-daubois** [comment]
There's definitely room for new features of course, but I think this can be used in production now 🙂 I removed this line from the README and published a new release, I think the API is pretty final and as I want it to be.

Thank you for your interest and I'd be happy to fix things if you encounter bugs! 😄
